// Code generated by go generate; DO NOT EDIT.

package httpapi

import (
	"context"
	"time"

	"currency-rate-aggregator/internal/domain"
)

type fakeRateFetcher struct {
	result   domain.RateResult
	results  map[string]domain.RateResult
	err      error
	currency string
	calls    []string
}

func (f *fakeRateFetcher) FetchRates(ctx context.Context, currency string) (domain.RateResult, error) {
	if err := ctx.Err(); err != nil {
		return domain.RateResult{}, err
	}
	f.currency = currency
	f.calls = append(f.calls, currency)
	if f.err != nil {
		return domain.RateResult{}, f.err
	}
	if f.results != nil {
		return f.results[currency], nil
	}
	return f.result, nil
}

type fakeRateHistoryReader struct {
	rates    []domain.CurrencyRate
	err      error
	currency string
	limit    int
	from     time.Time
	to       time.Time
}

func (f *fakeRateHistoryReader) History(ctx context.Context, currency string, limit int) ([]domain.CurrencyRate, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	f.currency = currency
	f.limit = limit
	if f.err != nil {
		return nil, f.err
	}
	return f.rates, nil
}

func (f *fakeRateHistoryReader) HistoryByDate(ctx context.Context, currency string, from, to time.Time, limit int) ([]domain.CurrencyRate, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	f.currency = currency
	f.from = from
	f.to = to
	f.limit = limit
	if f.err != nil {
		return nil, f.err
	}
	return f.rates, nil
}
