CREATE TABLE IF NOT EXISTS rates (
	id BIGSERIAL PRIMARY KEY,
	currency TEXT NOT NULL,
	buy DOUBLE PRECISION NOT NULL,
	sell DOUBLE PRECISION NOT NULL,
	bank TEXT NOT NULL,
	fetched_at TIMESTAMPTZ NOT NULL
);
